MARORKA_USERNAME = "reports@technomar.gr"
MARORKA_PASSWORD = "Technomar123!"
MARORKA_AUTH_METHOD = "digest"
MARORKA_TOKEN = ""
DASHBOARD_PASSWORD = "321908"
DASHBOARD_BACKGROUND_IMAGE = "06626d6c-ataman-dpg-panathinaikos-olympiacos.jpg"
